### ISSUE TITLE
Pagination manquante

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/dcLog#1]
Je suppose que tu l'as vu, la pagination n'est pas active quand on liste les logs.

**Comment by franck-paul** [comment]
Fichier index.php, ligne 49, remplacer :

```php
    $logs_counter = $logs->count();
```

par :

```php
    $logs_counter = dcCore::app()->log->getLogs($params, true)->f(0);
```

**Comment by franck-paul** [comment]
Ce qui me laisse penser que j'ai un souci avec le ->count() sur un dcRecord :-/
Ou plutôt qu'il y a un souci avec espace de nom vs pas d'espace de nom, plutôt.

**Comment by franck-paul** [comment]
Oups, je viens de faire la mise à jour, j'avais une vielle version. Je ferme et te dirai si nouveau souci.

**Comment by JcDenis** [comment]
Il y a quelques corrections (dont une suivant un fix récent sur Dotclear) dans les tuyaux pour celui-ci, faut juste que je prenne 5 minutes pour synchro le dépôt :)
